Update contents.lr
.iteritems() does not work in python3/jinja2

```
...
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)                                                                                                                                                                                                                     
Started source info update                                                                                                                                                                                                                                                      
Finished source info update in 0.03 sec                                                                                                                                                                                                                                         
Started build                                                                                                                                                                                                                                                                   
U index.html                                                                                                                                                                                                                                                                    
  E index.html (jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'iteritems')                                                                                                                                                                
U kontakt/index.html                                                                                                                                                                                                                                                            
  E kontakt/index.html (jinja2.exceptions.UndefinedError: 'collections.OrderedDict object' has no attribute 'iteritems')                                                                                                                                                        
U projects/index.html                                                                                                                                     
...`