fix(markdown-link-classes): fix for mistune 2
Mistune 2 does not always pass a `text` or `title` parameter to the
renderer's `link` method. This (when building with the Lektor 3.4
pre-release branch) was resulting in a `"TypeError: link()
missing 2 required positional arguments: 'text' and 'title'"`
exception when rendering /blog/plugin-play (which has a bare URL in
it's markdown content.)